version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "22:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "in progress"
      - "dependencies"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "22:45"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      python-packages:
        patterns:
          - "*"
    labels:
      - "in progress"
      - "dependencies"
