name: Pre-commit

on:
  pull_request_target:
  push:
    branches: [main]
  # pull_request:
  #   types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: |
            3.12
      - name: Install Dependencies
        run: |
          pip install pre-commit
          pre-commit install
      - name: Pre-commit and auto commit
        run: |
          pre-commit run --all-files || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Update files
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          signoff: true
          branch: pre-commit
          # base: main
          title: "🔨 Update files by <github-actions[bot]>"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            wait
            in progress
            bot
          draft: false
          delete-branch: true
          sign-commits: true
